#!/bin/sh
BBWP_DIR=`dirname "$0"`
if [ `uname` = "Darwin" ]; then
    "$BBWP_DIR/third_party/node/mac/node" "$BBWP_DIR/lib/bbwp.js" "$@"
else
    "$BBWP_DIR/third_party/node/linux/node" "$BBWP_DIR/lib/bbwp.js" "$@"
fi
